### ISSUE TITLE
Question about the license

### ISSUE THREAD

**Issue by ikatalan** [dlukashev/android-phone-number-with-flags#2]
Hello,

Just saw your great work on the android country/phone selector component. It's just what I need.
I also saw that you have two Licenses in the repo: one under the Apache license agreement which state that this component is actually an open source. and a second one which states that NO ONE can re-use this component.

https://github.com/dlukashev/android-phone-number-with-flags

Can you please remove the copyright notice that forbid the use of your open source component ? Or at least change so people could use it ?

/*
 * Copyright (c) 2014 Amberfog.
 *
 * This source code is Amberfog Confidential Proprietary
 * This software is protected by copyright. All rights and titles are reserved.
 * You shall not use, copy, distribute, modify, decompile, disassemble or reverse
 * engineer the software. Otherwise this violation would be treated by law and
 * would be subject to legal prosecution. Legal use of the software provides
 * receipt of a license from the right holder only.
 */

Thanks and Happy coding!!!!

**Comment by dlukashev** [comment]
fixed. sorry for that

**Comment by ikatalan** [comment]
THANKS MAN! 
I really appreciate your effort
